# vim: set ft=yaml ts=2 expandtab:
---

name: CI

on:

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
    - cron: '40 11 * * 6'

jobs:

  CI:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - centos7
        - centos8
        - oraclelinux8
        - ubuntu-16.04
        - ubuntu-18.04
        - ubuntu-20.04
        - fedora32
        - fedora33
        - debian9
        - debian10

        ansible_version:
        - '2.9'
        - '2.10'

        include:

        - target: centos7
          distribution: centos
          version: 7
          privileged: false

        - target: centos8
          distribution: centos
          version: 8
          privileged: false

        - target: oraclelinux8
          distribution: oraclelinux
          version: 8-slim
          privileged: false

        - target: ubuntu-16.04
          distribution: ubuntu
          version: xenial
          privileged: false

        - target: ubuntu-18.04
          distribution: ubuntu
          version: bionic
          privileged: false

        - target: ubuntu-20.04
          distribution: ubuntu
          version: focal
          privileged: false

        - target: fedora32
          distribution: fedora
          version: 32
          privileged: true

        - target: fedora33
          distribution: fedora
          version: 33
          privileged: true

        - target: debian9
          distribution: debian
          version: stretch
          privileged: false

        - target: debian10
          distribution: debian
          version: buster
          privileged: true

    env:
      
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_CONTAINER_IMAGE: ${{ matrix.distribution }}
      CI_CONTAINER_TAG: ${{ matrix.version }}
      CI_CONTAINER_PRIVILEGED: ${{ matrix.privileged }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
 
    defaults:
      run:
        working-directory: ansible_collections/mafalb/postfix

    steps:

    - name: checkout collection mafalb.postfix
      uses: actions/checkout@v2
      with:
        path: ansible_collections/mafalb/postfix

    - name: install dependencies
      run: ansible-galaxy collection install -r molecule/requirements.yml

    - name: install molecule
      run: ansible-playbook -D molecule/install_molecule.yml -e molecule_ansible_version=${{ matrix.ansible_version }} -t all,debug

    - name: check ansible version
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        ansible --version | grep "^ansible ${{ matrix.ansible_version }}"

    - name: molecule tests
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test

...
